openapi: 3.0.3
info:
  title: Claerance
  description: Claerance
  version: 1.0.0
servers:
  - url: 'https://your-domain.tld'
paths:
  /auth:
    get:
      responses:
        200:
          description: "Authentication successful"
        303:
          description: "Authentication unsuccessful, redirecting to login page."
      summary: "Authenticate to clearance"
  /session:
    post:
      summary: "Login and create new session"
      responses:
        201:
          description: "Session created"
        403:
          description: "Not authorized"
    delete:
      responses:
        200:
          description: "Session deleted"
  /session/{id}:
    delete:
      responses:
        200:
          description: "Session deleted"
  /user/list:
    get:
      responses:
        200:
          description: "Get list of all users"
        401:
          description: "No authorisation provided"
        403:
          description: "Not authorized"
  /user/{id}:
    get:
      responses:
        200:
          description: "Get detailed information about user"
        404:
          description: "No user with this id found"
    put:
      responses:
        200:
          description: "User info successfully updated"
        404:
          description: "No user with this id found"
    delete:
      responses:
        204:
          description: "User successfully deleted"
        404:
          description: "No user with this id found"
  /user/create:
    post:
      responses:
        201:
          description: "User successfully created"

  /sites/list:
    get:
      responses:
        200:
          description: "List all sites known to claerance"

  /sites/{id}:
    get:
      responses:
        200:
          description: "Get detailed information about a site"
        404:
          description: "No site with this id was found"
    put:
      responses:
        200:
          description: "Update information about a site"
        404:
          description: "No site with this id was found"
    delete:
      responses:
        204:
          description: "Delete site"
        404:
          description: "No site with this id was found"
