swagger: "2.0"
info:
  title: Claerance
  description: Claerance
  version: 1.0.0
host: your-domain.tld
basePath: /api
schemes:
  - https
paths:
  /auth:
    get:
      responses:
        200:
          description: "Authentication successful"
        303:
          description: "Authentication unsuccessful, redirecting to login page."
      summary: "Authenticate to clearance"
  /session:
    post:
      responses:
        201:
          description: "Session created"
        403:
          description: "Not authorized"
    delete:
      responses:
        200:
          description: "Session deleted"
  /session/{id}:
    delete:
      responses:
        200:
          description: "Session deleted"
  /user/list:
    get:
      responses:
        200:
          description: "Get list of all users"
        401:
          description: "No authorisation provided"
        403:
          description: "Not authorized"
  /user/{id}:
    get:
      responses:
        200:
          description: "Get detailed information about user"
    put:
      responses:
        200:
          description: "User info successfully updated"
  /user/create:
    post:
      responses:
        201:
          description: "User successfully created"
